### ISSUE TITLE
Gene Symbol normalization methods.

### ISSUE THREAD

**Issue by YaoXinZhi** [funRiceGenes/funRiceGenes.github.io#1]
Dear Pro. @venyao 
Can I know how you mapped the gene symbol to MSUID and RAPID? Is there a full mapping file, or is it manually marked.
Because I did not find a gene name normalization tool with high accuracy, although I tried to map the gene symbol to the Entrez ID.

Best Regards

Xinzhi Yao

**Comment by venyao** [comment]
![image](https://user-images.githubusercontent.com/5529672/83368695-5b719080-a3ec-11ea-933b-9505d9aef1cc.png)

Please check the publication of funRiceGenes in GigaScience (doi: 10.1093/gigascience/gix119) for more information.

Actually, we mapped the gene symbol to MSUID and RAPID by manually check the published papers.
